In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.2'

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros_like(np.array([1, 2, 3]))

array([0, 0, 0])

In [7]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 1, 11) # Inclusive of 2 ends

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(n[1, 2], n[1][2])

n[0, 0] = 10
print(n)

n[1] = 20
print(n)

n[:, 0] = 30
print(n)

6 6
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[10  2  3]
 [20 20 20]
 [ 7  8  9]]
[[30  2  3]
 [30 20 20]
 [30  8  9]]


In [14]:
np.random.rand(3, 3)

array([[0.80134412, 0.74155448, 0.87548093],
       [0.45019205, 0.98105457, 0.82879365],
       [0.92101919, 0.92603044, 0.33423942]])

In [15]:
n.mean()

np.float64(16.88888888888889)

In [16]:
n.std()

np.float64(11.009535709702288)

In [17]:
n.min()

np.int64(2)