In [1]:
import numpy as np

In [2]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

In [3]:
u * v # Element-wise multiplication

array([ 4, 10, 18])

In [10]:
u.dot(v), np.sum(u*v) # Vector dot product

(np.int64(32), np.int64(32))

In [14]:
U = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
V = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])

In [15]:
U.shape, V.shape

((4, 3), (3, 4))

In [21]:
# Matrix multiplication
V.dot(U), U.dot(V), np.matmul(V, U), np.matmul(U, V), U @ V

(array([[268, 314, 360],
        [356, 418, 480],
        [444, 522, 600]]),
 array([[ 92,  98, 104, 110],
        [218, 233, 248, 263],
        [344, 368, 392, 416],
        [470, 503, 536, 569]]),
 array([[268, 314, 360],
        [356, 418, 480],
        [444, 522, 600]]),
 array([[ 92,  98, 104, 110],
        [218, 233, 248, 263],
        [344, 368, 392, 416],
        [470, 503, 536, 569]]),
 array([[ 92,  98, 104, 110],
        [218, 233, 248, 263],
        [344, 368, 392, 416],
        [470, 503, 536, 569]]))

In [23]:
I = np.eye(3) # Identity matrix
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
sq = np.array([[1, 2], [3, 4]])
inv = np.linalg.inv(sq)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
sq.dot(inv) # Identity, not very close

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [29]:
np.allclose(sq.dot(inv), np.eye(2)) # Check with tolerance

True